source 'https://rubygems.org'

# Benutze RoR version 3.2.3 
gem 'rails', '3.2.3'

# Composite (multiple primary keys)
gem 'composite_primary_keys'

# Login-Manager
gem 'devise'

#Listendarstellung
gem 'will_paginate'

# Datenformat JSON
gem 'json'

# Benutze MySQL
group :production, :development, :test do
	gem 'mysql2'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platform => :ruby
  gem 'uglifier', '>= 1.0.3'
end

gem "jquery-rails", "~> 2.1.3"

# Deployen mit Capistrano
gem 'capistrano'

# Testing Environment
# RSpec: Behaviour-Driven Development tool
gem "rspec-rails", :group => [:test, :development]
group :test do
  # Factory Girl ersetzt die RoR Fixtures 
  gem "factory_girl_rails"

  # Capybara führt Benutzerinteraktionen aus
  gem "capybara"

  # Guard führt bei jedem speichern die Tests (Specs) aus
  gem "guard-rspec"

  # Gem das fake Namen, Vorname, E-Mail Adressen und Co generiert
  gem "faker"
end